locales-path: Avicus/locales
max-group-imbalance: 0.20
libraries:
  - path: maps
    ignored-directories:
      - Dev
      - Storage
  - github: true
    path: Avicus/atlas-maps
rotation:
  path: plugins/Atlas/rotation.xml
  restart-on-end: false
  randomize: false
  auto-start: true
delete-matches: true
scrimmage: false
github:
  auth: false
  username: username
  token: your token # https://github.com/settings/tokens
website:
  base: https://alm-was.here
  # {0} = map slug
  map: maps/map/{0}/

send-deprecation-warnings: true

freeze:
  enabled: true
  radius:
    extinguish: 15
    tnt: 15

chat:
  strip-color: true # Remove color codes from chat sent by users

channels:
  enabled: true
  reports:
    enabled: true
    # The time, in seconds, a player must wait between reports.
    cooldown: 15
  staff:
    enabled: true